import { c as create_ssr_component } from "../../../chunks/ssr.js";
const _page_svelte_svelte_type_style_lang = "";
const css = {
  code: "body.svelte-192d4hi.svelte-192d4hi{margin:0;padding:0;font-family:Georgia}.welcome.svelte-192d4hi.svelte-192d4hi{position:relative;top:-10px;margin-bottom:10px;animation:svelte-192d4hi-fadeIn ease-in 2s}.fade-in.svelte-192d4hi.svelte-192d4hi{opacity:0;animation:svelte-192d4hi-fadeInStretchOut ease-in-out 4s;animation-delay:2s;animation-fill-mode:forwards;line-height:2;margin:10px 0;font-size:25px}.section.svelte-192d4hi.svelte-192d4hi{overflow:hidden;display:flex;flex-direction:row;justify-content:center;align-items:center;white-space:nowrap;padding:20px;box-sizing:border-box;text-align:center;width:100%;border-top:2px solid #888;line-height:3}.section1.svelte-192d4hi.svelte-192d4hi{height:600px;background-color:#3498db;color:#fff}.section2.svelte-192d4hi.svelte-192d4hi,.section3.svelte-192d4hi.svelte-192d4hi{height:400px;background-color:#FEF9FF;color:#3498db}.section4.svelte-192d4hi.svelte-192d4hi{height:450px;background-color:#3498db;color:#fff;flex-direction:row}.section4.svelte-192d4hi div.svelte-192d4hi{flex:1;display:flex;flex-direction:column;align-items:center}.section5.svelte-192d4hi.svelte-192d4hi{height:500px;background-color:#FEF9FF;color:#3498db}h1.svelte-192d4hi.svelte-192d4hi{font-size:48px;font-family:Georgia;margin-bottom:10px;margin-top:20px}@keyframes svelte-192d4hi-fadeIn{0%{opacity:0}100%{opacity:1}}@keyframes svelte-192d4hi-fadeInStretchOut{0%{opacity:0;transform:scale(0)}100%{opacity:1}}p.svelte-192d4hi.svelte-192d4hi{animation:svelte-192d4hi-fadeInStretchOut ease-in-out 4s;animation-delay:2s}",
  map: null
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `<body class="svelte-192d4hi" data-svelte-h="svelte-w84zi6"><div class="section section1 svelte-192d4hi"><div><h1 class="welcome svelte-192d4hi">Why Plato?</h1> <p class="fade-in svelte-192d4hi">Unlock your potential with a mentor by your side, guiding you through your career or academic journey.</p> <p class="fade-in svelte-192d4hi">Mentorship is at the heart of what we do.</p></div></div> <div class="section section2 svelte-192d4hi"><div><h1 class="svelte-192d4hi">Connecting Dreams and Expertise</h1> <p class="fade-in svelte-192d4hi">Plato brings together passionate learners and seasoned professionals,</p> <p class="fade-in svelte-192d4hi">creating a dynamic synergy that propels you towards greatness.</p></div></div> <div class="section section3 svelte-192d4hi"><div><h1 class="svelte-192d4hi">Personalized Mentorship</h1> <p class="fade-in svelte-192d4hi">Experience the art of personalization.</p> <p class="fade-in svelte-192d4hi">We pair you with mentors who understand your unique goals and aspirations, providing tailored support.</p></div></div> <div class="section section4 svelte-192d4hi"><div class="svelte-192d4hi"><h1 class="svelte-192d4hi">Trust and Community</h1> <p class="fade-in svelte-192d4hi">Plato is your sanctuary for forging genuine and meaningful connections.</p> <p class="fade-in svelte-192d4hi">Join our community of learners and mentors and start your journey to success.</p></div></div> <div class="section section5 svelte-192d4hi"><div><h1 class="svelte-192d4hi">Thank You for Allowing Us to Share About Our Values</h1></div></div></body>`;
});
export {
  Page as default
};
