import { c as create_ssr_component } from "../../../../chunks/ssr.js";
const _page_svelte_svelte_type_style_lang = "";
const css = {
  code: ".privacy-policy-page.svelte-73iqcz.svelte-73iqcz{font-size:16px;line-height:1.5;margin:350px auto 0;max-width:800px;padding:20px;text-align:justify}h1.svelte-73iqcz.svelte-73iqcz,h2.svelte-73iqcz.svelte-73iqcz{font-size:24px;margin-bottom:10px;text-align:center}.privacy-policy-page.svelte-73iqcz .gradient-text-blue.svelte-73iqcz:hover{transform:scale(1.05);cursor:pointer}.gradient-text.svelte-73iqcz.svelte-73iqcz{background:linear-gradient(rgb(80, 101, 168), rgb(11, 20, 119));-webkit-background-clip:text;background-clip:text;color:transparent}.gradient-text-blue.svelte-73iqcz.svelte-73iqcz{background:linear-gradient(rgb(73, 131, 250), rgb(58, 103, 193));-webkit-background-clip:text;background-clip:text;color:transparent}",
  map: null
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `<div class="privacy-policy-page svelte-73iqcz" data-svelte-h="svelte-1pfu1dc"><h2 class="svelte-73iqcz"><strong class="gradient-text svelte-73iqcz">Privacy Policy</strong></h2> <br> <h1 class="svelte-73iqcz">Welcome to Plato&#39;s Privacy Policy page. This Privacy Policy explains how we collect, use, disclose, and safeguard your personal information when you use our website and services.</h1> <br> <h2 class="svelte-73iqcz"><strong class="gradient-text svelte-73iqcz">Information We Collect</strong></h2> <p>We may collect various types of information, including but not limited to your name, email address, and usage data when you interact with our website or use our services.</p> <br> <h2 class="svelte-73iqcz"><strong class="gradient-text svelte-73iqcz">How We Use Your Information</strong></h2> <p>We use the information we collect to provide, improve, and personalize our services. This includes communicating with you, analyzing usage patterns, and ensuring the security of your information.</p> <br> <h2 class="svelte-73iqcz"><strong class="gradient-text svelte-73iqcz">Sharing Your Information</strong></h2> <p>We do not sell, trade, or otherwise transfer your personal information to third parties. Your privacy is important to us, and we take steps to protect your information from unauthorized access or disclosure.</p> <br> <h2 class="svelte-73iqcz"><strong class="gradient-text svelte-73iqcz">Contacting Us</strong></h2> <p>If you have any questions or concerns about our Privacy Policy, please contact us:</p> <ul><li>Email: <a href="mailto:privacy@plato.com" class="gradient-text-blue svelte-73iqcz">privacy@plato.com</a></li> <li>Phone: <span class="gradient-text-blue svelte-73iqcz">+1 (123) 456-7890</span></li></ul> <br> <h2 class="svelte-73iqcz"><strong class="gradient-text svelte-73iqcz">Updates to This Policy</strong></h2> <p>We may update this Privacy Policy to reflect changes in our practices. It&#39;s recommended to review this page periodically for any updates. The latest revision date will be indicated at the top of the page.</p> <br> <br> <br> <br> <br></div>`;
});
export {
  Page as default
};
